# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_url_link',
            field=models.URLField(default='/meetup/index.html'),
        ),
        migrations.AddField(
            model_name='participant',
            name='participant_email',
            field=models.EmailField(default='john@doe.com', max_length=254),
        ),
    ]
