# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_auto_20160803_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantaddress',
            name='id',
        ),
        migrations.AlterField(
            model_name='participantaddress',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meetup.Participant'),
        ),
    ]
