# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 21:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0004_event_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('E', 'Eat'), ('D', 'Drink')], default='D', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 14, 21, 8, 51, 633257, tzinfo=utc)),
        ),
    ]
