# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 22:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0005_auto_20160814_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 14, 22, 23, 50, 409138, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='participantaddress',
            name='country',
            field=models.CharField(default='France', max_length=50),
        ),
    ]
