# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 17:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0008_auto_20160815_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantaddress',
            name='street_number',
        ),
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 15, 17, 25, 7, 130024, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 15, 19, 25, 7, 130524, tzinfo=utc)),
        ),
    ]
