# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 17:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0009_auto_20160815_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 15, 17, 40, 22, 896131, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 15, 19, 40, 22, 896630, tzinfo=utc)),
        ),
    ]
