# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 18:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0010_auto_20160815_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 15, 18, 21, 28, 227973, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 15, 20, 21, 28, 228467, tzinfo=datetime.timezone.utc)),
        ),
    ]
