# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 19:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0011_auto_20160815_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 15, 19, 14, 49, 81086, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 15, 21, 14, 49, 81086, tzinfo=utc)),
        ),
    ]
