# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 21:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0014_auto_20160816_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantaddress',
            name='participant',
        ),
        migrations.AddField(
            model_name='participant',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='country',
            field=models.CharField(default='France', max_length=50),
        ),
        migrations.AddField(
            model_name='participant',
            name='postal_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='street_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 16, 21, 26, 13, 323488, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 16, 23, 26, 13, 323989, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_message',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ParticipantAddress',
        ),
    ]
