# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 22:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0015_auto_20160816_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_key',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 16, 22, 59, 29, 411962, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 17, 0, 59, 29, 412461, tzinfo=utc)),
        ),
    ]
