# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 00:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0017_auto_20160817_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='latitude',
            field=models.DecimalField(decimal_places=17, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='longitude',
            field=models.DecimalField(decimal_places=17, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 20, 0, 26, 52, 449624, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 20, 2, 26, 52, 450124, tzinfo=utc)),
        ),
    ]
