# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 22:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0018_auto_20160820_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatheringlocation',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meetup.Event'),
        ),
        migrations.AddField(
            model_name='gatheringlocation',
            name='location_address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 21, 22, 9, 46, 307137, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 22, 0, 9, 46, 308137, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gatheringlocation',
            name='location_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
