# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 22:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0019_auto_20160822_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 21, 22, 10, 6, 968987, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 22, 0, 10, 6, 969994, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gatheringlocation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.Event'),
        ),
    ]
