# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 20:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0020_auto_20160822_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=200, null=True)),
                ('postal_code', models.CharField(max_length=10, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(default='France', max_length=50)),
                ('latitude', models.DecimalField(decimal_places=17, default=0.0, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=17, default=0.0, max_digits=20)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 22, 20, 28, 21, 602186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 22, 22, 28, 21, 602668, tzinfo=utc)),
        ),
    ]
