# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 21:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0021_auto_20160822_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('PA', 'Participant address'), ('GLA', 'Gathering location address')], default='GLA', max_length=3),
        ),
        migrations.AddField(
            model_name='address',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetup.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 23, 21, 58, 10, 272631, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 23, 23, 58, 10, 273147, tzinfo=utc)),
        ),
    ]
