# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 23:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0022_auto_20160823_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 23, 23, 3, 9, 198001, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 24, 1, 3, 9, 198501, tzinfo=utc)),
        ),
    ]
