# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 20:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0024_auto_20161002_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatheringlocation',
            name='query_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 2, 20, 43, 9, 222536, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 2, 22, 43, 9, 223536, tzinfo=utc)),
        ),
    ]
