# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 20:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0025_auto_20161002_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatheringlocation',
            old_name='query_name',
            new_name='href',
        ),
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 2, 20, 54, 16, 4790, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 2, 22, 54, 16, 4790, tzinfo=utc)),
        ),
    ]
