# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 20:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0027_auto_20161002_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='participant_message',
        ),
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 31, 20, 29, 58, 776954, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 31, 22, 29, 58, 776954, tzinfo=utc)),
        ),
    ]
