# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 22:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0028_auto_20161031_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='full_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='full_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 3, 22, 16, 8, 407868, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 4, 0, 16, 8, 407868, tzinfo=utc)),
        ),
    ]
